openapi: 3.2.0
info:
  title: Vultr VPCs API
  version: '2.0'
  contact:
    email: support@vultr.com
    name: ''
    url: https://www.vultr.com
  description: 'Operations tagged VPCs across 2 of this provider''s published API definitions: vultr-v2-openapi.yaml, vultr-openapi.yml. Each path carries the servers of the definition it was published in.'
servers:
- url: https://api.vultr.com/v2
security:
- API Key: []
tags:
- description: VPCs are fully isolated networks accessible only by instances on your account. Each VPC is only available in one region and cannot span across regions. An instance can connect to multiple VPCs and you may have up to 5 VPCs per region.
  name: VPCs
  x-displayName: VPCs
paths:
  /vpcs/{vpc-id}:
    delete:
      description: Delete a VPC.
      operationId: delete-vpc
      parameters:
      - description: The [VPC ID](#operation/list-vpcs).
        explode: false
        in: path
        name: vpc-id
        required: true
        schema:
          type: string
        style: simple
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - API Key: []
      summary: Delete a VPC
      tags:
      - VPCs
      x-codeSamples:
      - lang: Curl
        source: "curl \"https://api.vultr.com/v2/vpcs/{vpc-id}\" \\\n  -X DELETE \\\n  -H \"Authorization: Bearer ${VULTR_API_KEY}\""
      x-accepts: application/json
    get:
      description: Get information about a VPC.
      operationId: get-vpc
      parameters:
      - description: The [VPC ID](#operation/list-vpcs).
        explode: false
        in: path
        name: vpc-id
        required: true
        schema:
          type: string
        style: simple
      responses:
        '200':
          content:
            application/json:
              examples:
                response:
                  value:
                    vpc:
                      id: cb676a46-66fd-4dfb-b839-443f2e6c0b60
                      date_created: 2020-10-10 01:56:20+00:00
                      region: ewr
                      description: Example VPC Description
                      v4_subnet: 10.99.0.0
                      v4_subnet_mask: 24
              schema:
                $ref: '#/components/schemas/get_vpc_200_response'
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - API Key: []
      summary: Get a VPC
      tags:
      - VPCs
      x-codeSamples:
      - lang: Curl
        source: "curl \"https://api.vultr.com/v2/vpcs/{vpc-id}\" \\\n  -X GET \\\n  -H \"Authorization: Bearer ${VULTR_API_KEY}\""
      x-accepts: application/json
    put:
      description: Update information for a VPC.
      operationId: update-vpc
      parameters:
      - description: The [VPC ID](#operation/list-vpcs).
        explode: false
        in: path
        name: vpc-id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            examples:
              request:
                value:
                  description: Example VPC
            schema:
              $ref: '#/components/schemas/update_vpc_request'
        description: Include a JSON object in the request body with a content type of **application/json**.
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - API Key: []
      summary: Update a VPC
      tags:
      - VPCs
      x-codeSamples:
      - lang: Curl
        source: "curl \"https://api.vultr.com/v2/vpcs/{vpc-id}\" \\\n  -X PUT \\\n  -H \"Authorization: Bearer ${VULTR_API_KEY}\" \\\n  -H \"Content-Type: application/json\" \\\n  --data '{\n    \"description\" : \"Example VPC\"\n  }'"
      x-content-type: application/json
      x-accepts: application/json
    servers:
    - url: https://api.vultr.com/v2
  /vpcs:
    get:
      description: Get a list of all VPCs in your account.
      operationId: list-vpcs
      parameters:
      - description: Number of items requested per page. Default is 100 and Max is 500.
        explode: true
        in: query
        name: per_page
        required: false
        schema:
          type: integer
        style: form
      - description: Cursor for paging. See [Meta and Pagination](#section/Introduction/Meta-and-Pagination).
        explode: true
        in: query
        name: cursor
        required: false
        schema:
          type: string
        style: form
      responses:
        '200':
          content:
            application/json:
              examples:
                response:
                  value:
                    vpcs:
                    - id: cb676a46-66fd-4dfb-b839-443f2e6c0b60
                      region: ewr
                      date_created: 2020-10-10 01:56:20+00:00
                      description: Example VPC Description
                      v4_subnet: 10.99.0.0
                      v4_subnet_mask: 24
                    meta:
                      total: 1
                      links:
                        next: ''
                        prev: ''
              schema:
                $ref: '#/components/schemas/list_vpcs_200_response'
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - API Key: []
      summary: List VPCs
      tags:
      - VPCs
      x-codeSamples:
      - lang: Curl
        source: "curl \"https://api.vultr.com/v2/vpcs\" \\\n  -X GET \\\n  -H \"Authorization: Bearer ${VULTR_API_KEY}\""
      x-accepts: application/json
    post:
      description: 'Create a new VPC in a `region`. VPCs should use RFC1918 private address space:


        10.0.0.0 - 10.255.255.255 (10/8 prefix)

        172.16.0.0 - 172.31.255.255 (172.16/12 prefix)

        192.168.0.0 - 192.168.255.255 (192.168/16 prefix)'
      operationId: create-vpc
      requestBody:
        content:
          application/json:
            examples:
              example:
                value:
                  region: ewr
                  description: Example VPC
                  v4_subnet: 10.99.0.0
                  v4_subnet_mask: 24
            schema:
              $ref: '#/components/schemas/create_vpc_request'
        description: Include a JSON object in the request body with a content type of **application/json**.
      responses:
        '201':
          content:
            application/json:
              examples:
                response:
                  value:
                    network:
                      id: cb676a46-66fd-4dfb-b839-443f2e6c0b60
                      date_created: 2020-10-10 01:56:20+00:00
                      region: ewr
                      description: Example VPC
                      v4_subnet: 10.99.0.0
                      v4_subnet_mask: 24
              schema:
                $ref: '#/components/schemas/get_vpc_200_response'
          description: Created
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      security:
      - API Key: []
      summary: Create a VPC
      tags:
      - VPCs
      x-codeSamples:
      - lang: Curl
        source: "curl \"https://api.vultr.com/v2/vpcs\" \\\n  -X POST \\\n  -H \"Authorization: Bearer ${VULTR_API_KEY}\" \\\n  -H \"Content-Type: application/json\" \\\n  --data '{\n    \"region\" : \"ewr\",\n    \"description\" : \"Example VPC\",\n    \"v4_subnet\" : \"10.99.0.0\",\n    \"v4_subnet_mask\" : 24\n  }'"
      x-content-type: application/json
      x-accepts: application/json
    servers:
    - url: https://api.vultr.com/v2
components:
  schemas:
    create_vpc_request:
      properties:
        region:
          description: Create the VPC in this [Region id](#operation/list-regions).
          type: string
        description:
          description: A description of the VPC.
          type: string
        v4_subnet:
          description: 'The IPv4 VPC address. For example: 10.99.0.0<br><span style="color: red">If v4_subnet_mask is specified then v4_subnet is a required field.</span>'
          type: string
        v4_subnet_mask:
          description: 'The number of bits for the netmask in CIDR notation. Example: 24<br><span style="color: red">If v4_subnet is specified then v4_subnet_mask is a required field.</span>'
          type: integer
      required:
      - region
      type: object
    meta:
      description: The meta information object. See [Meta and Pagination](#section/Introduction/Meta-and-Pagination) for more information.
      example:
        total: 0
        links:
          next: next
          prev: prev
      properties:
        total:
          description: Total objects available in the list. This value may be greater than the number of objects returned if `per_page` is set.
          type: integer
        links:
          $ref: '#/components/schemas/meta_links'
      title: meta
      type: object
      x-examples:
        meta response:
          meta:
            total: 31
            links:
              next: WxYzExampleNext
              prev: ''
    vpc:
      description: VPC information.
      example:
        date_created: date_created
        v4_subnet_mask: 0
        description: description
        v4_subnet: v4_subnet
        id: id
        region: region
      properties:
        id:
          description: A unique ID for the VPC.
          type: string
        region:
          description: The [Region id](#operation/list-regions) where the VPC is located.
          type: string
        date_created:
          description: Date the VPC was created.
          type: string
        description:
          description: A description of the VPC.
          type: string
        v4_subnet:
          description: 'The IPv4 VPC address. For example: 10.99.0.0'
          type: string
        v4_subnet_mask:
          description: 'The number of bits for the netmask in CIDR notation. Example: 24'
          type: integer
      required:
      - id
      title: vpc
      type: object
      x-examples:
        example:
          id: cb676a46-66fd-4dfb-b839-443f2e6c0b60
          date_created: 2020-10-10 01:56:20+00:00
          region: ewr
          description: Example VPC
          v4_subnet: 10.99.0.0
          v4_subnet_mask: 24
      x-tags:
      - VPCs
    get_vpc_200_response:
      example:
        vpc:
          date_created: date_created
          v4_subnet_mask: 0
          description: description
          v4_subnet: v4_subnet
          id: id
          region: region
      properties:
        vpc:
          $ref: '#/components/schemas/vpc'
      type: object
    list_vpcs_200_response:
      example:
        meta:
          total: 0
          links:
            next: next
            prev: prev
        vpcs:
        - date_created: date_created
          v4_subnet_mask: 0
          description: description
          v4_subnet: v4_subnet
          id: id
          region: region
        - date_created: date_created
          v4_subnet_mask: 0
          description: description
          v4_subnet: v4_subnet
          id: id
          region: region
      properties:
        vpcs:
          items:
            $ref: '#/components/schemas/vpc'
          type: array
        meta:
          $ref: '#/components/schemas/meta'
      type: object
    meta_links:
      description: Cursor values for pagination.
      example:
        next: next
        prev: prev
      properties:
        next:
          description: Cursor value for the next page.
          type: string
        prev:
          description: Cursor value for the previous page.
          type: string
      type: object
    update_vpc_request:
      properties:
        description:
          description: The VPC description.
          type: string
      required:
      - description
      type: object
  securitySchemes:
    API_Key:
      description: "The Vultr API v2 uses API keys for authentication. You can manage your API keys in the Vultr customer portal. Please do not share API keys publicly, or embed them in client-side code. It is a good security practice to restrict their use by IP address in the [customer portal](https://my.vultr.com/settings/#settingsapi).\n\nTo authenticate a request, send your API Key as a bearer token in the request header.\n\n### Authentication Example\n\n    curl \"https://api.vultr.com/v2/account\" \\\n      -X GET \\\n      -H \"Authorization: Bearer ${VULTR_API_KEY}\"\n\nUnauthenticated API requests will fail. All requests must use HTTPS encryption for security, and calls made with HTTP will fail."
      in: header
      scheme: bearer
      type: http
x-refined-from:
- vultr-v2-openapi.yaml
- vultr-openapi.yml
